name: PROD (scraper)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/sharechat-scraper
          tags: ${{ steps.vars.outputs.sha_short }}
