name: Deploy to production

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/sharechat-scraper
          tags: ${{ steps.vars.outputs.sha_short }}

      - name: Publish the daily scraper version to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/sharechat-scraper
          tags: "cron-latest"

      - name: Deploy to k8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_KEY }}
          script: |
            ./autodeploy_scs.sh ${{ steps.vars.outputs.sha_short }} >> ~/deploy.log 2>&1
